"""Recipient encrypted sharing"""

from alembic import op
import sqlalchemy as sa

revision = "c83bcb1e8f9d"
down_revision = "5ed0bae65059"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shares",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column("wrapped_key", sa.String(length=1024), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("expires", sa.Integer(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shares_recipient_id"), "shares", ["recipient_id"], unique=False)
    op.create_index(op.f("ix_shares_sender_id"), "shares", ["sender_id"], unique=False)
    op.create_table(
        "sharing_keys",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("public_key", sa.String(length=2048), nullable=False),
        sa.Column("private_key", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sharing_keys")
    op.drop_index(op.f("ix_shares_sender_id"), table_name="shares")
    op.drop_index(op.f("ix_shares_recipient_id"), table_name="shares")
    op.drop_table("shares")
    # ### end Alembic commands ###
